name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Static build"
      - name: Deploy
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./
          production-deploy: true
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
